### ISSUE TITLE
SDK Not working at all

### ISSUE THREAD

**Issue by CodeWithKamal** [tolgee/flutter-sdk#8]
I tried using Tolgee self-host with API key and URL, then I tried using Tolgee cloud, then I tried it in static mode. every time is just threw following error:

```
E/flutter ( 8076): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter ( 8076): #0      Iterable.firstWhere (dart:core/iterable.dart:703:5)
E/flutter ( 8076): #1      TolgeeStaticTranslations.init (package:tolgee/src/translations/tolgee_static_translations.dart:79:31)
E/flutter ( 8076): <asynchronous suspension>
E/flutter ( 8076): #2      TolgeeTranslationsStrategy.initStatic (package:tolgee/src/translations/tolgee_translation_strategy.dart:34:5)
E/flutter ( 8076): <asynchronous suspension>
E/flutter ( 8076): #3      Tolgee.init (package:tolgee/src/sdk/tolgee.dart:32:11)
```

I followed the example of tolgee pub.dev package.

so my point is, `Tolgee.supportedLocales` is returning empty list. in all 3 modes.

**Comment by CodeWithKamal** [comment]
okay, I was able to run in static mode with json instead of arb file. but how to use it directly from cloud or self-hosted. using api key and api url. what is API url ? and which API key should we use ? there is no proper docs for this.

**Comment by Anty0** [comment]
Hi. Thanks for the report!
In the error you've sent, the library tries to initialize in the static mode, and since there are no translations available, it fails to set the default locale. In future releases, I'll add a more descriptive exception to make what's happening more understandable.

To initialize the app in remote mode, you have to set both the `apiKey` and `apiUrl`. The correct URL for Tolgee cloud is `https://app.tolgee.io/v2`. If the initialization in remote mode fails, send the error you are getting there.

**Comment by CodeWithKamal** [comment]
yes, initialization is failing in remote mode. let me share the error message.

**Comment by CodeWithKamal** [comment]
I'm getting
```
Bad state: No element
```

`Tolgee.supportedLocales` is returning empty list. 

in remote mode.

**Comment by CodeWithKamal** [comment]
![Screenshot_1731576105](https://github.com/user-attachments/assets/758b9fb0-98f8-4b42-a72c-b14252b4c766)

**Comment by Anty0** [comment]
Are there any errors in the log before that? I think it failed to pull the translations. Could you check if you have the correct URL set? Unfortunately, it is different from our other SDKs at the moment.
Sorry for the trouble. The Flutter SDK is still in its early stages and needs more care.

**Comment by CodeWithKamal** [comment]
yes, url is correct.

**Comment by CodeWithKamal** [comment]
here is the full log.
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building App(dirty, state: _AppState#8f80c):
Bad state: No element

The relevant error-causing widget was:
    App App:file:///Users/<mymacname>/projects/<project-name>/lib/main.dart:36:32

When the exception was thrown, this was the stack:
#0      List.first (dart:core-patch/growable_array.dart:344:5)
growable_array.dart:344
#1      _AppState.build (package:<myprojectname>/app.dart:102:36)
app.dart:102
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:27)
framework.dart:5729
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
framework.dart:5617
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
framework.dart:5780
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
framework.dart:5333
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599:5)
framework.dart:5599
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771:11)
framework.dart:5771
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
framework.dart:5593
...     Normal element mounting (63 frames)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
framework.dart:4468
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
framework.dart:3963
#73     _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:441:16)
view.dart:441
#74     _RawViewElement.mount (package:flutter/src/widgets/view.dart:464:5)
view.dart:464
...     Normal element mounting (15 frames)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
framework.dart:4468
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
framework.dart:3963
#91     RootElement._rebuild (package:flutter/src/widgets/binding.dart:1605:16)
binding.dart:1605
#92     RootElement.mount (package:flutter/src/widgets/binding.dart:1574:5)
binding.dart:1574
#93     RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1527:18)
binding.dart:1527
#94     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
framework.dart:3038
#95     RootWidget.attach (package:flutter/src/widgets/binding.dart:1526:13)
binding.dart:1526
#96     WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1265:27)
binding.dart:1265
#97     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1247:5)
binding.dart:1247
#98     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1233:7)
binding.dart:1233
#102    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
isolate_patch.dart:184
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════
D/EGL_emulation( 8734): app_time_stats: avg=790141.75ms min=790141.75ms max=790141.75ms count=1
```

**Comment by CodeWithKamal** [comment]
there is no other error message in console, and this error message is pointing to `Tolgee.supportedLocales` .

**Comment by Anty0** [comment]
Well, that throws all of the simple solutions out the window 😄

Would it be possible for you to send me the whole log? Feel free to do so in the DM on our Slack (https://join.slack.com/t/tolgeecommunity/shared_invite/zt-195isb5u8-_RcSRgVJfvgsPpOBIok~IQ). Thank you!

**Comment by CodeWithKamal** [comment]
> here is the full log.
> 
> ```
> ════════ Exception caught by widgets library ═══════════════════════════════════
> The following StateError was thrown building App(dirty, state: _AppState#8f80c):
> Bad state: No element
> 
> The relevant error-causing widget was:
>     App App:file:///Users/<mymacname>/projects/<project-name>/lib/main.dart:36:32
> 
> When the exception was thrown, this was the stack:
> #0      List.first (dart:core-patch/growable_array.dart:344:5)
> growable_array.dart:344
> #1      _AppState.build (package:<myprojectname>/app.dart:102:36)
> app.dart:102
> #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:27)
> framework.dart:5729
> #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
> framework.dart:5617
> #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
> framework.dart:5780
> #5      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
> framework.dart:5333
> #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599:5)
> framework.dart:5599
> #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771:11)
> framework.dart:5771
> #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
> framework.dart:5593
> ...     Normal element mounting (63 frames)
> #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
> framework.dart:4468
> #72     Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
> framework.dart:3963
> #73     _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:441:16)
> view.dart:441
> #74     _RawViewElement.mount (package:flutter/src/widgets/view.dart:464:5)
> view.dart:464
> ...     Normal element mounting (15 frames)
> #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
> framework.dart:4468
> #90     Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
> framework.dart:3963
> #91     RootElement._rebuild (package:flutter/src/widgets/binding.dart:1605:16)
> binding.dart:1605
> #92     RootElement.mount (package:flutter/src/widgets/binding.dart:1574:5)
> binding.dart:1574
> #93     RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1527:18)
> binding.dart:1527
> #94     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
> framework.dart:3038
> #95     RootWidget.attach (package:flutter/src/widgets/binding.dart:1526:13)
> binding.dart:1526
> #96     WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1265:27)
> binding.dart:1265
> #97     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1247:5)
> binding.dart:1247
> #98     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1233:7)
> binding.dart:1233
> #102    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
> isolate_patch.dart:184
> (elided 3 frames from class _Timer and dart:async-patch)
> 
> ════════════════════════════════════════════════════════════════════════════════
> D/EGL_emulation( 8734): app_time_stats: avg=790141.75ms min=790141.75ms max=790141.75ms count=1
> ```

this is the full log. 
as soon as my app opens I see red screen and this error in console. and my app gets stuck here.

**Comment by CodeWithKamal** [comment]
> Well, that throws all of the simple solutions out the window 😄
> 
> Would it be possible for you to send me the whole log? Feel free to do so in the DM on our Slack (https://join.slack.com/t/tolgeecommunity/shared_invite/zt-195isb5u8-_RcSRgVJfvgsPpOBIok~IQ). Thank you!

slack link is not working.

**Comment by Anty0** [comment]
> slack link is not working.

Oh, it looks like it expired.
Try this one: https://tolg.ee/slack

**Comment by Anty0** [comment]
> this is the full log. as soon as my app opens I see red screen and this error in console. and my app gets stuck here.

🤔 I'll try to reproduce the issue
What platform are you testing the app on? (Web, Android, etc.)
Most of these wired issues seem to be related to the differences between them.

**Comment by CodeWithKamal** [comment]
> > this is the full log. as soon as my app opens I see red screen and this error in console. and my app gets stuck here.
> 
> 🤔 I'll try to recreate the issue What platform are you testing the app on? (Web, Android, etc.) Most of these wired issues seem to be related to the differences between them.

same issue with Android & iOS both. I tested on latest iOS 18 simulator and android 14 emulator.
I'm using flutter version : 
```
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (3 weeks ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3
```

**Comment by CodeWithKamal** [comment]
it's working now auto magically.
